# NGUON CO BAN
title: Lưu Giang Nam
first_name: Nam
last_name: Lưu Giang
description: Lecturer • Data Science Researcher

# THONG TIN LIEN HE
email: luugiangnam.math@gmail.com
github_username: luugiangnam
linkedin_username: ten-linkedin-cua-ban
researchgate_username: ten-researchgate-cua-ban
