# NGUỒN CƠ BẢN
title: Lưu Giang Nam             
first_name: Nam
last_name: Lưu Giang
description: Lecturer • Data Science Researcher

# THÔNG TIN LIÊN HỆ & MẠNG XÃ HỘI
email: luugiangnam.math@gmail.com
github_username: luugiangnam
linkedin_username: ten-linkedin-cua-ban # Điền username thực tế
researchgate_username: ten-researchgate-cua-ban # Điền username thực tế
